// Single source of truth for every artist/project page + the
// landing page grid.
//
// Auto-generated by scripts/sync-artists.js — don't hand-edit the images
// arrays, re-running the script will overwrite them with whatever files
// are in img/<slug>/. Hand-written fields (name, category, credit,
// heroAlt, lede, and any alt/caption/position already set on an image)
// are preserved.
//
// category is "live" or "editorial" — descriptive metadata only. New
// artists default to "live"; change it by hand for editorial work.
//
// To add or update a project:
//   1. Drop its photos in img/<slug>/ (numbered 01.jpg, 02.jpg, ...).
//      Name whichever one should be the cover (used on index/live/
//      editorial + the project page) "hero.jpg", or suffix an existing
//      number with "_hero" (e.g. 03_hero.jpg). If none is marked, the
//      first image below is used.
//   2. Run: node scripts/sync-artists.js
// No new HTML file needed — projects/artist.html renders any slug via
// artist.html?a=<slug>, and the grid order follows this array.
window.ARTISTS = [
  {
    slug: "wizkid",
    name: "Wizkid",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Wizkid performing live",
    lede: "Live stage — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Wizkid — Cover", caption: "Cover", position: "center 30%" },
      { file: "02.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "03.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "04.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "05.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "06.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "07.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "08.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "010.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Wizkid — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "tyla",
    name: "Tyla",
    category: "live",
    credit: "for Giants of Africa",
    heroAlt: "Tyla performing at Giants of Africa Festival, Kigali",
    lede: "Live at Giants of Africa Festival, Kigali — a guest set that closed with a hug from Masai Ujiri.",
    images: [
      { file: "01.jpg", alt: "Tyla — Live", caption: "Live" },
      { file: "02.jpg", alt: "Tyla — With the dancers", caption: "With the dancers" },
      { file: "03.jpg", alt: "Tyla — Mid-set", caption: "Mid-set" },
      { file: "04.jpg", alt: "Tyla — Water break", caption: "Water break" },
      { file: "05.jpg", alt: "Tyla — Arms up", caption: "Arms up" },
      { file: "06.jpg", alt: "Tyla — With Masai Ujiri", caption: "With Masai Ujiri" },
      { file: "07.jpg", alt: "Tyla — Full stride", caption: "Full stride" },
      { file: "hero.jpg", alt: "Tyla — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "davido",
    name: "Davido",
    category: "live",
    credit: "for Giants of Africa",
    heroAlt: "Davido performing live",
    lede: "Live performance. Heat, jewelry, a white shirt in green stage light.",
    images: [
      { file: "hero.jpg", alt: "Davido — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "ayra-starr",
    name: "Ayra Starr",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Ayra Starr performing live",
    lede: "Live, from the pit. Smoke, phones, the whole field leaning forward.",
    images: [
      { file: "01.jpg", alt: "Ayra Starr — From the pit", caption: "From the pit", position: "30% 55%" },
      { file: "02.jpg", alt: "Ayra Starr — Live", caption: "Live" },
      { file: "03.jpg", alt: "Ayra Starr — Live", caption: "Live" },
      { file: "04.jpg", alt: "Ayra Starr — Live", caption: "Live" },
      { file: "05.jpg", alt: "Ayra Starr — Live", caption: "Live" },
      { file: "06.jpg", alt: "Ayra Starr — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Ayra Starr — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "tiwa-savage",
    name: "Tiwa Savage",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Tiwa Savage performing live",
    lede: "Live. Command of the stage, held in a still.",
    images: [
      { file: "0-12.jpg", alt: "Tiwa Savage — Live", caption: "Live" },
      { file: "0-13.jpg", alt: "Tiwa Savage — Live", caption: "Live" },
      { file: "0-14.jpg", alt: "Tiwa Savage — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Tiwa Savage — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "black-sheriff",
    name: "Black Sheriff",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Black Sheriff performing live",
    lede: "Live. Ghana on the road, caught mid-phrase.",
    images: [
      { file: "01.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "02.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "03.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "04.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "05.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "06.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Black Sheriff — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "musa-keys",
    name: "Musa Keys",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Musa Keys performing live",
    lede: "Live. A quieter pocket inside the night.",
    images: [
      { file: "hero.jpg", alt: "Musa Keys — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "pher",
    name: "Pher",
    category: "editorial",
    credit: "SPICE cover",
    heroAlt: "Pher — SPICE cover art",
    lede: "Cover art for SPICE by Pher — studio color, denim, braid pulled taut.",
    images: [
      { file: "01_hero.jpg", alt: "Pher — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "adekunle",
    name: "Adekunle",
    category: "live",
    credit: "for DukeConcept",
    heroAlt: "Adekunle performing at Tio Tequila Bar",
    lede: "Live at Tio Tequila Bar — an intimate room, phones up for every chorus.",
    images: [
      { file: "01.jpg", alt: "Adekunle — Live", caption: "Live" },
      { file: "02.jpg", alt: "Adekunle — Close", caption: "Close" },
      { file: "03.jpg", alt: "Adekunle — Full house", caption: "Full house" },
      { file: "04.jpg", alt: "Adekunle — Reach", caption: "Reach" },
      { file: "05.jpg", alt: "Adekunle — From the crowd", caption: "From the crowd" },
      { file: "06.jpg", alt: "Adekunle — With the band", caption: "With the band" },
      { file: "07.jpg", alt: "Adekunle — Sing it back", caption: "Sing it back" },
      { file: "09.jpg", alt: "Adekunle — Live", caption: "Live" },
      { file: "10.jpg", alt: "Adekunle — Encore", caption: "Encore" },
      { file: "hero.jpg", alt: "Adekunle — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "bnxn",
    name: "Bnxn",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Bnxn performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "02.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "03.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "04.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "05.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "06.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "08.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Bnxn — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "enny",
    name: "Enny",
    category: "live",
    credit: "for her Solo Tour",
    heroAlt: "Enny performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "02.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "03.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "04.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "05.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "07.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "08.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "09.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "010.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "011.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "012.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "013.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "014.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Enny — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "ruger",
    name: "Ruger",
    category: "live",
    credit: "for DukeConcept",
    heroAlt: "Ruger performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "02.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "03.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "04.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "05.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "06.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "07.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Ruger — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "thuy",
    name: "Thuy",
    category: "live",
    credit: "for Wings World Tour",
    heroAlt: "Thuy performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "02.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "03.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "04.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "05.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "07.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "08.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "09.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Thuy — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "ishusho",
    name: "Ishusho",
    category: "editorial",
    credit: "live",
    heroAlt: "Ishusho performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "02.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "03.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "04.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "05.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "06.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "07.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "08.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "09.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "010.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "012.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "013.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "014.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "015.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "016.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "017.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "018.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "019.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "020.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "021.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "022.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "023.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "024.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "025.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "026.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "027.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "028.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "029.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "030.jpg", alt: "Ishusho — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Ishusho — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "mustafa",
    name: "Mustafa",
    category: "editorial",
    credit: "live",
    heroAlt: "Mustafa performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "02.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "03.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "04.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "05.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "06.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "07.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "08.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "09.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "010.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "011.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "012.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "013.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Mustafa — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "simi",
    name: "Simi",
    category: "live",
    credit: "for DukeConcept",
    heroAlt: "Simi performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Simi — Live", caption: "Live" },
      { file: "02.jpg", alt: "Simi — Live", caption: "Live" },
      { file: "03.jpg", alt: "Simi — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Simi — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "brima",
    name: "Brima",
    category: "editorial",
    credit: "Campaign shoot",
    heroAlt: "Brima performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "02.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "03.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "04.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "05.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "06.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "07.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "08.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "09.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "010.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Brima — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "lesley",
    name: "Lesley",
    category: "editorial",
    credit: "AfroSexy Summer cover",
    heroAlt: "Lesley performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "02.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "03.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "04.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "05.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "hero.jpg", alt: "Lesley — Cover", caption: "Cover" }
    ]
  }
];
