// Single source of truth for every artist page + the homepage index.
//
// Auto-generated by scripts/sync-artists.js — don't hand-edit the images
// arrays, re-running the script will overwrite them with whatever files
// are in img/<slug>/. Hand-written fields (name, credit, heroAlt, lede,
// and any alt/caption/position already set on an image) are preserved.
//
// To add or update an artist:
//   1. Drop their photos in img/<slug>/ (numbered 01.jpg, 02.jpg, ...).
//      Name whichever one should show on the homepage + artist-page cover
//      with a "_hero" suffix (e.g. 03_hero.jpg). If none is marked, the
//      first image in the list below is used instead.
//   2. Run: node scripts/sync-artists.js
// No new HTML file needed — projects/artist.html renders any slug via
// artist.html?a=<slug>, and the homepage list/nav order follows this array.
window.ARTISTS = [
  {
    slug: "wizkid",
    name: "Wizkid",
    credit: "live",
    heroAlt: "Wizkid performing live",
    lede: "Live stage — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Wizkid — Cover", caption: "Cover", position: "center 30%" },
      { file: "02.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "03.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "04.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "05.jpg", alt: "Wizkid — Live", caption: "Live" }
    ]
  },
  {
    slug: "tyla",
    name: "Tyla",
    credit: "for Giants of Africa",
    heroAlt: "Tyla performing at Giants of Africa Festival, Kigali",
    lede: "Live at Giants of Africa Festival, Kigali — a guest set that closed with a hug from Masai Ujiri.",
    images: [
      { file: "01_hero.jpg", alt: "Tyla — Cover", caption: "Cover" },
      { file: "02.jpg", alt: "Tyla — With the dancers", caption: "With the dancers" },
      { file: "03.jpg", alt: "Tyla — Mid-set", caption: "Mid-set" },
      { file: "04.jpg", alt: "Tyla — Water break", caption: "Water break" },
      { file: "05.jpg", alt: "Tyla — Arms up", caption: "Arms up" },
      { file: "06.jpg", alt: "Tyla — With Masai Ujiri", caption: "With Masai Ujiri" },
      { file: "07.jpg", alt: "Tyla — Full stride", caption: "Full stride" }
    ]
  },
  {
    slug: "davido",
    name: "Davido",
    credit: "live",
    heroAlt: "Davido performing live",
    lede: "Live performance. Heat, jewelry, a white shirt in green stage light.",
    images: [
      { file: "01_hero.jpg", alt: "Davido — Cover", caption: "Cover" }
    ]
  },
  {
    slug: "ayra-starr",
    name: "Ayra Starr",
    credit: "live",
    heroAlt: "Ayra Starr performing live",
    lede: "Live, from the pit. Smoke, phones, the whole field leaning forward.",
    images: [
      { file: "01.jpg", alt: "Ayra Starr — From the pit", caption: "From the pit", position: "30% 55%" }
    ]
  },
  {
    slug: "tiwa-savage",
    name: "Tiwa Savage",
    credit: "live",
    heroAlt: "Tiwa Savage performing live",
    lede: "Live. Command of the stage, held in a still.",
    images: [
      { file: "01.jpg", alt: "Tiwa Savage — From the pit", caption: "From the pit", position: "30% 55%" }
    ]
  },
  {
    slug: "black-sheriff",
    name: "Black Sheriff",
    credit: "live",
    heroAlt: "Black Sheriff performing live",
    lede: "Live. Ghana on the road, caught mid-phrase.",
    images: [
      { file: "01_hero.jpg", alt: "Black Sheriff — Cover", caption: "Cover" },
      { file: "02.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "03.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "04.jpg", alt: "Black Sheriff — Live", caption: "Live" }
    ]
  },
  {
    slug: "musa-keys",
    name: "Musa Keys",
    credit: "live",
    heroAlt: "Musa Keys performing live",
    lede: "Live. A quieter pocket inside the night.",
    images: [
      { file: "01.jpg", alt: "Musa Keys — From the pit", caption: "From the pit", position: "30% 55%" }
    ]
  },
  {
    slug: "pher",
    name: "Pher",
    credit: "SPICE cover",
    heroAlt: "Pher — SPICE cover art",
    lede: "Cover art for SPICE by Pher — studio color, denim, braid pulled taut.",
    images: [
      { file: "01.jpg", alt: "Pher — Frame", caption: "Frame", position: "30% 55%" }
    ]
  },
  {
    slug: "adekunle",
    name: "Adekunle",
    credit: "live",
    heroAlt: "Adekunle performing at Tio Tequila Bar",
    lede: "Live at Tio Tequila Bar — an intimate room, phones up for every chorus.",
    images: [
      { file: "01.jpg", alt: "Adekunle — Live", caption: "Live" },
      { file: "02.jpg", alt: "Adekunle — Close", caption: "Close" },
      { file: "03.jpg", alt: "Adekunle — Full house", caption: "Full house" },
      { file: "04.jpg", alt: "Adekunle — Reach", caption: "Reach" },
      { file: "05.jpg", alt: "Adekunle — From the crowd", caption: "From the crowd" },
      { file: "06.jpg", alt: "Adekunle — With the band", caption: "With the band" },
      { file: "07.jpg", alt: "Adekunle — Sing it back", caption: "Sing it back" },
      { file: "08.jpg", alt: "Adekunle — Between songs", caption: "Between songs" },
      { file: "09_hero.jpg", alt: "Adekunle — Pretty Girl", caption: "Pretty Girl" },
      { file: "10.jpg", alt: "Adekunle — Encore", caption: "Encore" }
    ]
  },
  {
    slug: "bnxn",
    name: "Bnxn",
    credit: "live",
    heroAlt: "Bnxn performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "02.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "03.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "04.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "05.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "06.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "07_hero.jpg", alt: "Bnxn — Cover", caption: "Cover" },
      { file: "08.jpg", alt: "Bnxn — Live", caption: "Live" }
    ]
  },
  {
    slug: "enny",
    name: "Enny",
    credit: "live",
    heroAlt: "Enny performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "01.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "02.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "03.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "04.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "05.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "06_hero.jpg", alt: "Enny — Cover", caption: "Cover" },
      { file: "07.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "08.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "09.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "010.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "011.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "012.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "013.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "014.jpg", alt: "Enny — Live", caption: "Live" }
    ]
  }
];
