// Single source of truth for every artist/project page + the
// landing page grid.
//
// Auto-generated by scripts/sync-artists.js — don't hand-edit the images
// arrays, re-running the script will overwrite them with whatever files
// are in img/<slug>/. Hand-written fields (name, category, credit,
// heroAlt, lede, and any alt/caption/position already set on an image)
// are preserved.
//
// category is "live" or "editorial" — descriptive metadata only. New
// artists default to "live"; change it by hand for editorial work.
//
// To add or update a project:
//   1. Drop its photos in img/<slug>/ (numbered 01.jpg, 02.jpg, ...).
//      Name whichever one should be the cover (used on the landing grid
//      + opens the project page's carousel first) "hero.jpg", or suffix
//      an existing number with "_hero" (e.g. 03_hero.jpg) — it's moved
//      to the front of the list below regardless of where it sorts. If
//      none is marked, the first image below is used.
//   2. Run: node scripts/sync-artists.js
// No new HTML file needed — projects/artist.html renders any slug via
// artist.html?a=<slug>, and the grid order follows this array.
window.ARTISTS = [
  {
    slug: "wizkid",
    name: "Wizkid",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Wizkid performing live",
    lede: "Live stage — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Wizkid — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Wizkid — Cover", caption: "Cover", position: "center 30%" },
      { file: "02.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "03.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "04.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "05.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "06.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "07.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "08.jpg", alt: "Wizkid — Live", caption: "Live" },
      { file: "010.jpg", alt: "Wizkid — Live", caption: "Live" }
    ]
  },
  {
    slug: "thuy",
    name: "Thuy",
    category: "live",
    credit: "for Wings World Tour",
    heroAlt: "Thuy performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Thuy — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "02.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "03.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "04.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "05.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "07.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "08.jpg", alt: "Thuy — Live", caption: "Live" },
      { file: "09.jpg", alt: "Thuy — Live", caption: "Live" }
    ]
  },
  {
    slug: "pher",
    name: "Pher",
    category: "editorial",
    credit: "SPICE cover",
    heroAlt: "Pher — SPICE cover art",
    lede: "Cover art for SPICE by Pher — studio color, denim, braid pulled taut.",
    images: [
      { file: "hero.jpg", alt: "Pher — Cover", caption: "Cover" },
      { file: "02.jpg", alt: "Pher — Live", caption: "Live" },
      { file: "03.jpg", alt: "Pher — Live", caption: "Live" },
      { file: "04.jpg", alt: "Pher — Live", caption: "Live" },
      { file: "05.jpg", alt: "Pher — Live", caption: "Live" },
      { file: "06.jpg", alt: "Pher — Live", caption: "Live" },
      { file: "07.jpg", alt: "Pher — Live", caption: "Live" },
      { file: "08.jpg", alt: "Pher — Live", caption: "Live" }
    ]
  },
  {
    slug: "lesley",
    name: "Lesley",
    category: "editorial",
    credit: "AfroSexy Summer cover",
    heroAlt: "Lesley performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Lesley — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "02.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "03.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "04.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "05.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "06.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "07.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "08.jpg", alt: "Lesley — Live", caption: "Live" },
      { file: "09.jpg", alt: "Lesley — Live", caption: "Live" }
    ]
  },
  {
    slug: "tiwa-savage",
    name: "Tiwa Savage",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Tiwa Savage performing live",
    lede: "Live. Command of the stage, held in a still.",
    images: [
      { file: "hero.jpg", alt: "Tiwa Savage — Cover", caption: "Cover" },
      { file: "0-12.jpg", alt: "Tiwa Savage — Live", caption: "Live" },
      { file: "0-13.jpg", alt: "Tiwa Savage — Live", caption: "Live" },
      { file: "0-14.jpg", alt: "Tiwa Savage — Live", caption: "Live" }
    ]
  },
  {
    slug: "bobby-nsenga",
    name: "Bobby Nsenga",
    category: "live",
    credit: "for The Bobby Nsenga Experience",
    heroAlt: "Bobby Nsenga performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Bobby Nsenga — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Bobby Nsenga — Live", caption: "Live" },
      { file: "02.jpg", alt: "Bobby Nsenga — Live", caption: "Live" },
      { file: "03.jpg", alt: "Bobby Nsenga — Live", caption: "Live" },
      { file: "04.jpg", alt: "Bobby Nsenga — Live", caption: "Live" },
      { file: "05.jpg", alt: "Bobby Nsenga — Live", caption: "Live" },
      { file: "06.jpg", alt: "Bobby Nsenga — Live", caption: "Live" },
      { file: "07.jpg", alt: "Bobby Nsenga — Live", caption: "Live" }
    ]
  },
  {
    slug: "davido",
    name: "Davido",
    category: "live",
    credit: "for Giants of Africa",
    heroAlt: "Davido performing live",
    lede: "Live performance. Heat, jewelry, a white shirt in green stage light.",
    images: [
      { file: "hero.jpg", alt: "Davido — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Davido — Live", caption: "Live" },
      { file: "02.jpg", alt: "Davido — Live", caption: "Live" },
      { file: "04.jpg", alt: "Davido — Live", caption: "Live" },
      { file: "05.jpg", alt: "Davido — Live", caption: "Live" }
    ]
  },
  {
    slug: "adekunle",
    name: "Adekunle",
    category: "live",
    credit: "for DukeConcept",
    heroAlt: "Adekunle performing at Tio Tequila Bar",
    lede: "Live at Tio Tequila Bar — an intimate room, phones up for every chorus.",
    images: [
      { file: "hero.jpg", alt: "Adekunle — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Adekunle — Live", caption: "Live" },
      { file: "03.jpg", alt: "Adekunle — Full house", caption: "Full house" },
      { file: "04.jpg", alt: "Adekunle — Reach", caption: "Reach" },
      { file: "05.jpg", alt: "Adekunle — From the crowd", caption: "From the crowd" },
      { file: "06.jpg", alt: "Adekunle — With the band", caption: "With the band" },
      { file: "07.jpg", alt: "Adekunle — Sing it back", caption: "Sing it back" },
      { file: "08.jpg", alt: "Adekunle — Live", caption: "Live" },
      { file: "010.jpg", alt: "Adekunle — Live", caption: "Live" },
      { file: "011.jpg", alt: "Adekunle — Live", caption: "Live" }
    ]
  },
  {
    slug: "tyla",
    name: "Tyla",
    category: "live",
    credit: "for Giants of Africa",
    heroAlt: "Tyla performing at Giants of Africa Festival, Kigali",
    lede: "Live at Giants of Africa Festival, Kigali — a guest set that closed with a hug from Masai Ujiri.",
    images: [
      { file: "hero.jpg", alt: "Tyla — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Tyla — Live", caption: "Live" },
      { file: "02.jpg", alt: "Tyla — With the dancers", caption: "With the dancers" },
      { file: "03.jpg", alt: "Tyla — Mid-set", caption: "Mid-set" },
      { file: "04.jpg", alt: "Tyla — Water break", caption: "Water break" },
      { file: "05.jpg", alt: "Tyla — Arms up", caption: "Arms up" },
      { file: "06.jpg", alt: "Tyla — With Masai Ujiri", caption: "With Masai Ujiri" },
      { file: "07.jpg", alt: "Tyla — Full stride", caption: "Full stride" }
    ]
  },
  {
    slug: "enny",
    name: "Enny",
    category: "live",
    credit: "for her Solo Tour",
    heroAlt: "Enny performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Enny — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "02.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "03.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "04.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "05.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "07.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "08.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "09.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "010.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "011.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "012.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "013.jpg", alt: "Enny — Live", caption: "Live" },
      { file: "014.jpg", alt: "Enny — Live", caption: "Live" }
    ]
  },
  {
    slug: "ruger",
    name: "Ruger",
    category: "live",
    credit: "for DukeConcept",
    heroAlt: "Ruger performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Ruger — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "02.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "03.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "04.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "05.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "06.jpg", alt: "Ruger — Live", caption: "Live" },
      { file: "07.jpg", alt: "Ruger — Live", caption: "Live" }
    ]
  },
  {
    slug: "bnxn",
    name: "Bnxn",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Bnxn performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Bnxn — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "02.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "03.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "04.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "05.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "06.jpg", alt: "Bnxn — Live", caption: "Live" },
      { file: "08.jpg", alt: "Bnxn — Live", caption: "Live" }
    ]
  },
  {
    slug: "mustafa",
    name: "Mustafa",
    category: "editorial",
    credit: "live",
    heroAlt: "Mustafa performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Mustafa — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "02.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "03.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "04.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "05.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "06.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "07.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "08.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "09.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "010.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "011.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "012.jpg", alt: "Mustafa — Live", caption: "Live" },
      { file: "013.jpg", alt: "Mustafa — Live", caption: "Live" }
    ]
  },
  {
    slug: "simi",
    name: "Simi",
    category: "live",
    credit: "for DukeConcept",
    heroAlt: "Simi performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Simi — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Simi — Live", caption: "Live" },
      { file: "02.jpg", alt: "Simi — Live", caption: "Live" },
      { file: "03.jpg", alt: "Simi — Live", caption: "Live" }
    ]
  },
  {
    slug: "brima",
    name: "Brima",
    category: "editorial",
    credit: "Campaign shoot",
    heroAlt: "Brima performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Brima — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "02.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "03.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "04.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "05.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "06.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "07.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "08.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "09.jpg", alt: "Brima — Live", caption: "Live" },
      { file: "010.jpg", alt: "Brima — Live", caption: "Live" }
    ]
  },
  {
    slug: "ayra-starr",
    name: "Ayra Starr",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Ayra Starr performing live",
    lede: "Live, from the pit. Smoke, phones, the whole field leaning forward.",
    images: [
      { file: "hero.jpg", alt: "Ayra Starr — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Ayra Starr — From the pit", caption: "From the pit", position: "30% 55%" },
      { file: "02.jpg", alt: "Ayra Starr — Live", caption: "Live" },
      { file: "03.jpg", alt: "Ayra Starr — Live", caption: "Live" },
      { file: "04.jpg", alt: "Ayra Starr — Live", caption: "Live" },
      { file: "05.jpg", alt: "Ayra Starr — Live", caption: "Live" },
      { file: "06.jpg", alt: "Ayra Starr — Live", caption: "Live" },
      { file: "07.jpg", alt: "Ayra Starr — Live", caption: "Live" }
    ]
  },
  {
    slug: "black-sheriff",
    name: "Black Sheriff",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Black Sheriff performing live",
    lede: "Live. Ghana on the road, caught mid-phrase.",
    images: [
      { file: "hero.jpg", alt: "Black Sheriff — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "02.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "03.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "04.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "05.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "06.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "07.jpg", alt: "Black Sheriff — Live", caption: "Live" },
      { file: "014.jpg", alt: "Black Sheriff — Live", caption: "Live" }
    ]
  },
  {
    slug: "kingjames",
    name: "King James",
    category: "live",
    credit: "for 20 Years of King James",
    heroAlt: "King James performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Kingjames — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "02.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "03.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "04.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "05.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "06.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "07.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "08.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "09.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "010.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "011.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "012.jpg", alt: "Kingjames — Live", caption: "Live" },
      { file: "013.jpg", alt: "Kingjames — Live", caption: "Live" }
    ]
  },
  {
    slug: "mkgnmvmnts",
    name: "Mkgnmvmnts",
    category: "live",
    credit: "for Black and Loud Festival",
    heroAlt: "Mkgnmvmnts performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Mkgnmvmnts — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Mkgnmvmnts — Live", caption: "Live" },
      { file: "02.jpg", alt: "Mkgnmvmnts — Live", caption: "Live" },
      { file: "03.jpg", alt: "Mkgnmvmnts — Live", caption: "Live" },
      { file: "04.jpg", alt: "Mkgnmvmnts — Live", caption: "Live" },
      { file: "05.jpg", alt: "Mkgnmvmnts — Live", caption: "Live" },
      { file: "06.jpg", alt: "Mkgnmvmnts — Live", caption: "Live" },
      { file: "07.jpg", alt: "Mkgnmvmnts — Live", caption: "Live" },
      { file: "09.jpg", alt: "Mkgnmvmnts — Live", caption: "Live" }
    ]
  },
  {
    slug: "mustard",
    name: "Mustard",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Mustard performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Mustard — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Mustard — Live", caption: "Live" },
      { file: "02.jpg", alt: "Mustard — Live", caption: "Live" },
      { file: "03.jpg", alt: "Mustard — Live", caption: "Live" }
    ]
  },
  {
    slug: "personal-projects",
    name: "Personal Projects",
    category: "editorial",
    credit: "Personal work",
    heroAlt: "Personal Projects performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Personal Projects — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "02.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "03.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "04.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "05.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "06.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "07.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "08.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "09.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "010.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "012.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "013.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "014.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "015.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "016.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "017.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "018.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "019.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "020.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "021.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "022.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "023.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "024.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "025.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "026.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "027.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "028.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "029.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "030.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "031.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "032.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "033.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "034.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "035.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "036.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "037.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "038.jpg", alt: "Personal Projects — Live", caption: "Live" },
      { file: "039.jpg", alt: "Personal Projects — Live", caption: "Live" }
    ]
  },
  {
    slug: "pheelz",
    name: "Pheelz",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Pheelz performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Pheelz — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Pheelz — Live", caption: "Live" },
      { file: "02.jpg", alt: "Pheelz — Live", caption: "Live" },
      { file: "03.jpg", alt: "Pheelz — Live", caption: "Live" },
      { file: "04.jpg", alt: "Pheelz — Live", caption: "Live" },
      { file: "05.jpg", alt: "Pheelz — Live", caption: "Live" },
      { file: "06.jpg", alt: "Pheelz — Live", caption: "Live" },
      { file: "07.jpg", alt: "Pheelz — Live", caption: "Live" },
      { file: "08.jpg", alt: "Pheelz — Live", caption: "Live" }
    ]
  },
  {
    slug: "shaffy",
    name: "Shaffy",
    category: "live",
    credit: "live",
    heroAlt: "Shaffy performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Shaffy — Cover", caption: "Cover" },
      { file: "01.jpg", alt: "Shaffy — Live", caption: "Live" },
      { file: "02.jpg", alt: "Shaffy — Live", caption: "Live" },
      { file: "03.jpg", alt: "Shaffy — Live", caption: "Live" },
      { file: "05.jpg", alt: "Shaffy — Live", caption: "Live" },
      { file: "06.jpg", alt: "Shaffy — Live", caption: "Live" },
      { file: "07.jpg", alt: "Shaffy — Live", caption: "Live" },
      { file: "08.jpg", alt: "Shaffy — Live", caption: "Live" }
    ]
  },
  {
    slug: "shenseea",
    name: "Shenseea",
    category: "live",
    credit: "for Blastfest",
    heroAlt: "Shenseea performing live",
    lede: "Live — selected frames from the set.",
    images: [
      { file: "hero.jpg", alt: "Shenseea — Cover", caption: "Cover" },
      { file: "02.jpg", alt: "Shenseea — Live", caption: "Live" },
      { file: "03.jpg", alt: "Shenseea — Live", caption: "Live" },
      { file: "04.jpg", alt: "Shenseea — Live", caption: "Live" },
      { file: "05.jpg", alt: "Shenseea — Live", caption: "Live" },
      { file: "06.jpg", alt: "Shenseea — Live", caption: "Live" },
      { file: "07.jpg", alt: "Shenseea — Live", caption: "Live" },
      { file: "08.jpg", alt: "Shenseea — Live", caption: "Live" }
    ]
  }
];
