#!/usr/bin/env node
// Regenerates projects/artists-data.js from whatever's actually sitting in
// img/<slug>/. Run this after adding or removing photos from an artist's
// folder so the homepage + their gallery page reflect the real file list.
//
// Usage: node scripts/sync-artists.js
//
// Convention: name files 01.jpg, 02.jpg, ... in display order. Mark the one
// file that should be the homepage + gallery-page cover either by naming
// it exactly "hero.jpg" or by suffixing an existing number, e.g.
// "03_hero.jpg" — it doesn't need to be first, just present.
// Hand-written fields (name, category, credit, heroAlt, lede, and any
// alt/caption/position already set on a specific image) are preserved
// across re-runs; only the list of images is resynced to match the folder.
//
// `category` is "live" or "editorial" — descriptive metadata only, not
// used to route anything. New artists default to "live"; flip it by
// hand in artists-data.js if a shoot is editorial.

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.join(__dirname, "..");
const IMG_DIR = path.join(ROOT, "img");
const DATA_FILE = path.join(ROOT, "projects", "artists-data.js");
const IMAGE_EXT = /\.(jpe?g|png|webp)$/i;
const UNSUPPORTED_EXT = /\.(heic|heif|tiff?|raw|cr2|cr3|nef|arw)$/i;

function readExistingArtists() {
  const src = fs.readFileSync(DATA_FILE, "utf8");
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(src, sandbox);
  return sandbox.window.ARTISTS || [];
}

function naturalSort(a, b) {
  const na = parseInt((a.match(/^(\d+)/) || [])[1], 10);
  const nb = parseInt((b.match(/^(\d+)/) || [])[1], 10);
  if (!isNaN(na) && !isNaN(nb) && na !== nb) return na - nb;
  return a.localeCompare(b);
}

function titleCaseSlug(slug) {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function listFolderFiles(slug) {
  const folder = path.join(IMG_DIR, slug);
  const all = fs.readdirSync(folder);
  const unsupported = all.filter((f) => UNSUPPORTED_EXT.test(f));
  if (unsupported.length) {
    console.warn(
      `! img/${slug}/: skipping ${unsupported.length} unsupported file(s) (${unsupported.join(
        ", "
      )}) — convert to .jpg/.png/.webp first.`
    );
  }
  return all.filter((f) => IMAGE_EXT.test(f)).sort(naturalSort);
}

function buildArtist(slug, files, prior) {
  const name = (prior && prior.name) || titleCaseSlug(slug);
  const category = (prior && prior.category) || "live";
  const credit = (prior && prior.credit) || "live";
  const heroAlt = (prior && prior.heroAlt) || `${name} performing live`;
  const lede = (prior && prior.lede) || "Live — selected frames from the set.";
  const priorByFile = new Map(((prior && prior.images) || []).map((img) => [img.file, img]));

  const images = files.map((file) => {
    const existingImg = priorByFile.get(file);
    if (existingImg) return existingImg;
    const isHero = /(^|_)hero\./i.test(file);
    const caption = isHero ? "Cover" : "Live";
    return { file, alt: `${name} — ${caption}`, caption };
  });

  return { slug, name, category, credit, heroAlt, lede, images };
}

function q(str) {
  return JSON.stringify(str);
}

function serializeImage(img) {
  const parts = [`file: ${q(img.file)}`, `alt: ${q(img.alt)}`, `caption: ${q(img.caption)}`];
  if (img.position) parts.push(`position: ${q(img.position)}`);
  return `{ ${parts.join(", ")} }`;
}

function serializeArtist(a) {
  const imageLines = a.images.map((img) => "      " + serializeImage(img)).join(",\n");
  return (
    "  {\n" +
    `    slug: ${q(a.slug)},\n` +
    `    name: ${q(a.name)},\n` +
    `    category: ${q(a.category)},\n` +
    `    credit: ${q(a.credit)},\n` +
    `    heroAlt: ${q(a.heroAlt)},\n` +
    `    lede: ${q(a.lede)},\n` +
    "    images: [\n" +
    imageLines +
    "\n    ]\n" +
    "  }"
  );
}

const HEADER = `// Single source of truth for every artist/project page + the
// landing page grid.
//
// Auto-generated by scripts/sync-artists.js — don't hand-edit the images
// arrays, re-running the script will overwrite them with whatever files
// are in img/<slug>/. Hand-written fields (name, category, credit,
// heroAlt, lede, and any alt/caption/position already set on an image)
// are preserved.
//
// category is "live" or "editorial" — descriptive metadata only. New
// artists default to "live"; change it by hand for editorial work.
//
// To add or update a project:
//   1. Drop its photos in img/<slug>/ (numbered 01.jpg, 02.jpg, ...).
//      Name whichever one should be the cover (used on the landing grid
//      + the project page) "hero.jpg", or suffix an existing number
//      with "_hero" (e.g. 03_hero.jpg). If none is marked, the first
//      image below is used.
//   2. Run: node scripts/sync-artists.js
// No new HTML file needed — projects/artist.html renders any slug via
// artist.html?a=<slug>, and the grid order follows this array.
window.ARTISTS = [
`;

function main() {
  // Folders reserved for site chrome (not projects) — never synced as
  // artists, and dropped from the output if a stale entry exists.
  const RESERVED_SLUGS = ["about"];

  const existing = readExistingArtists().filter((a) => !RESERVED_SLUGS.includes(a.slug));
  const bySlug = new Map(existing.map((a) => [a.slug, a]));
  const existingOrder = existing.map((a) => a.slug);

  const folderSlugs = fs
    .readdirSync(IMG_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !RESERVED_SLUGS.includes(d.name))
    .map((d) => d.name)
    .sort();

  const finalArtists = [];

  existingOrder.forEach((slug) => {
    const prior = bySlug.get(slug);
    if (!folderSlugs.includes(slug)) {
      console.warn(`! img/${slug}/ is missing; keeping its existing entry unchanged.`);
      finalArtists.push(prior);
      return;
    }
    const files = listFolderFiles(slug);
    if (files.length === 0) {
      console.warn(`! img/${slug}/ has no photos; keeping its existing entry unchanged.`);
      finalArtists.push(prior);
      return;
    }
    const priorCount = (prior.images || []).length;
    if (files.length !== priorCount) {
      console.log(`~ ${slug}: ${priorCount} → ${files.length} photo(s)`);
    }
    finalArtists.push(buildArtist(slug, files, prior));
  });

  folderSlugs
    .filter((slug) => !existingOrder.includes(slug))
    .forEach((slug) => {
      const files = listFolderFiles(slug);
      if (files.length === 0) {
        console.warn(`! img/${slug}/ has no photos yet; skipping until it has at least one.`);
        return;
      }
      console.log(`+ ${slug}: new artist, ${files.length} photo(s)`);
      finalArtists.push(buildArtist(slug, files, null));
    });

  const body = finalArtists.map(serializeArtist).join(",\n");
  fs.writeFileSync(DATA_FILE, HEADER + body + "\n];\n");
  console.log(`\nSynced ${finalArtists.length} artist(s) → ${path.relative(ROOT, DATA_FILE)}`);
}

main();
